export const CLICK_ATTACK_MONSTER = "CLICK_ATTACK_MONSTER";
export const INCREASE_CLICK_DAMAGE = "INCREASE_CLICK_DAMAGE";
export const BUY_AUTO_ATTACKER = "BUY_AUTO_ATTACKER";
export const AUTO_ATTACK = "AUTO_ATTACK";
export const NEXT_LEVEL = "NEXT_LEVEL";
export const PREV_LEVEL = "PREV_LEVEL";
export const BOSS_FIGHT = "BOSS_FIGHT";
export const MORE_MONEY = "MORE_MONEY";
export const TOGGLE_AUTO_INCREASE = "TOGGLE_AUTO_INCREASE";
export const SAME_LEVEL = "SAME_LEVEL";

// SAGA FUNCTIONS
export const ATTACK_ASYNC = "ATTACK_ASYNC";
export const BUY_AUTO_ASYNC = "BUY_AUTO_ASYNC";
export const INCREASE_CLICK_DAMAGE_ASYNC = "INCREASE_CLICK_DAMAGE_ASYNC";
