export const CLICK_ATTACK_MONSTER = "CLICK_ATTACK_MONSTER";
export const INCREASE_CLICK_DAMAGE = "INCREASE_CLICK_DAMAGE";
export const BUY_AUTO_ATTACKER = "BUY_AUTO_ATTACKER";
export const AUTO_ATTACK = "AUTO_ATTACK";
export const NEXT_LEVEL = "NEXT_LEVEL";